/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: GY4N (https://sketchfab.com/GY4N)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/mercedes-amg-gt-black-series-2021-20db8f28297044ecb864c2e9e9dc19ad
title: Mercedes-AMG GT Black Series 2021
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import mercedes from "./mercedes-amg_gt_black_series_2021.glb";

export function Mercedes(props) {
  const { nodes, materials } = useGLTF(mercedes);
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={0}>
            <group
              position={[0, 5.11, 93.24]}
              rotation={[1.58, 0, 0]}
              scale={1000}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_5.geometry}
                material={materials.material_0}
              />
            </group>
            <group
              position={[-841.98, 1273.95, 351.78]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={1032.16}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_7.geometry}
                material={materials.material_1}
              />
            </group>
            <group
              position={[0, 5.11, 93.24]}
              rotation={[1.58, 0, 0]}
              scale={1000}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_9.geometry}
                material={materials.material_2}
              />
            </group>
            <group position={[815.74, -1360.38, 351.78]} scale={1000}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_11.geometry}
                material={materials.material_1}
              />
            </group>
            <group
              position={[0, 5.11, 93.24]}
              rotation={[1.58, 0, 0]}
              scale={1000}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_13.geometry}
                material={materials.material_0}
              />
            </group>
            <group
              position={[0, 5.11, 93.24]}
              rotation={[1.58, 0, 0]}
              scale={1000}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_15.geometry}
                material={materials.material_3}
              />
            </group>
            <group
              position={[0, 5.11, 93.24]}
              rotation={[1.58, 0, 0]}
              scale={1000}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_17.geometry}
                material={materials.material_4}
              />
            </group>
            <group
              position={[0, 5.11, 93.24]}
              rotation={[1.58, 0, 0]}
              scale={1000}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_19.geometry}
                material={materials.material_5}
              />
            </group>
            <group
              position={[0, 5.11, 93.24]}
              rotation={[1.58, 0, 0]}
              scale={1000}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_21.geometry}
                material={materials.material_6}
              />
            </group>
            <group
              position={[0, 5.11, 93.24]}
              rotation={[1.58, 0, 0]}
              scale={1000}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_23.geometry}
                material={materials.material_7}
              />
            </group>
            <group
              position={[-815.74, -1360.38, 351.78]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={1000}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_25.geometry}
                material={materials.material_1}
              />
            </group>
            <group
              position={[0, 5.11, 528.73]}
              rotation={[1.58, 0, 0]}
              scale={1000}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_28.geometry}
                material={materials.material_8}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_30.geometry}
                material={materials.material_9}
              />
            </group>
            <group
              position={[0, 5.11, 93.24]}
              rotation={[1.58, 0, 0]}
              scale={1000}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_32.geometry}
                material={materials.material_0}
              />
            </group>
            <group
              position={[0, 5.11, 93.24]}
              rotation={[1.58, 0, 0]}
              scale={1000}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_34.geometry}
                material={materials.material_0}
              />
            </group>
            <group
              position={[0, 5.11, 93.24]}
              rotation={[1.58, 0, 0]}
              scale={1000}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_36.geometry}
                material={materials.material_10}
              />
            </group>
            <group
              position={[0, 5.11, 93.24]}
              rotation={[1.58, 0, 0]}
              scale={1000}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_38.geometry}
                material={materials.material_11}
              />
            </group>
            <group
              position={[0, 5.11, 93.24]}
              rotation={[1.58, 0, 0]}
              scale={1000}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_40.geometry}
                material={materials.material_0}
              />
            </group>
            <group
              position={[0, 5.11, 93.24]}
              rotation={[1.58, 0, 0]}
              scale={1000}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_42.geometry}
                material={materials.material_12}
              />
            </group>
            <group
              position={[0, 5.11, 93.24]}
              rotation={[1.58, 0, 0]}
              scale={1000}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_44.geometry}
                material={materials.material_13}
              />
            </group>
            <group position={[841.98, 1273.95, 351.78]} scale={1032.16}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_46.geometry}
                material={materials.material_1}
              />
            </group>
            <group
              position={[0, 5.11, 93.24]}
              rotation={[1.58, 0, 0]}
              scale={1000}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_48.geometry}
                material={materials.material_14}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(mercedes);
