/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Veisun (https://sketchfab.com/Veisun)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/mercedes-benz-g55w263-amg-34fd2fc081014deab1240ab2a199920a
title: Mercedes-Benz G55/W263 (AMG)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import mercedes from "./mercedes-benz_g.glb";
import { useFrame } from "@react-three/fiber";

export function Mercedes(props) {
  const { nodes, materials } = useGLTF(mercedes);

  const ref = useRef();
  useFrame((state) => {
    const t = state.clock.getElapsedTime();
    ref.current.position.y = (1 + Math.sin(t / 2)) / 10;
    ref.current.rotation.set(
      ref.current.rotation.x,
      ref.current.rotation.y,
      0.1 + Math.cos(t / 4.5) / 2
    );
  });
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} ref={ref}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[-0.48, 0.26, 0.91]}
            rotation={[-2.96, 0, Math.PI]}
            scale={[0.63, 0.62, 0.62]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_4.geometry}
              material={materials["wheel_tire.FL"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_5.geometry}
              material={materials["wheel_chrome.FL"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6.geometry}
              material={materials["wheel_black.FL"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_7.geometry}
              material={materials["wheel_focus.FL"]}
            />
          </group>
          <group
            position={[0.47, 0.26, 0.91]}
            rotation={[-0.18, 0, 0]}
            scale={[0.63, 0.62, 0.62]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_9.geometry}
              material={materials["brake_disc.FL"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_10.geometry}
              material={materials["brake_disc.FL.001"]}
            />
          </group>
          <group
            position={[-0.48, 0.26, -0.91]}
            rotation={[-2.96, 0, -Math.PI]}
            scale={[0.63, 0.62, 0.62]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_12.geometry}
              material={materials["wheel_tire.RL"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_13.geometry}
              material={materials["wheel_chrome.RL"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_14.geometry}
              material={materials["wheel_black.RL"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_15.geometry}
              material={materials["wheel_focus.RL"]}
            />
          </group>
          <group
            position={[-0.48, 0.26, 0.91]}
            rotation={[-0.18, 0, 0]}
            scale={[-0.63, 0.62, 0.62]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_17.geometry}
              material={materials["brake_disc.FR.001"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_18.geometry}
              material={materials["brake_disc.FR"]}
            />
          </group>
          <group
            position={[0.48, 0.26, 0.91]}
            rotation={[-2.96, 0, Math.PI]}
            scale={[-0.63, 0.62, 0.62]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_20.geometry}
              material={materials["wheel_tire.FR"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_21.geometry}
              material={materials["wheel_chrome.FR"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_22.geometry}
              material={materials["wheel_black.FR"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_23.geometry}
              material={materials["wheel_focus.FR"]}
            />
          </group>
          <group
            position={[0.48, 0.26, -0.91]}
            rotation={[-2.96, 0, Math.PI]}
            scale={[-0.63, 0.62, 0.62]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_25.geometry}
              material={materials["wheel_tire.RR"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_26.geometry}
              material={materials["wheel_chrome.RR"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_27.geometry}
              material={materials["wheel_black.RR"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_28.geometry}
              material={materials["wheel_focus.RR"]}
            />
          </group>
          <group scale={0.3}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_30.geometry}
              material={materials["brake_disc.back"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_31.geometry}
              material={materials["brake_disc.back.001"]}
            />
          </group>
          <group rotation={[-Math.PI, 0, -Math.PI]} scale={0.56}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_33.geometry}
              material={materials.exhaust_chrome}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_34.geometry}
              material={materials.exhaust_focus}
            />
          </group>
          <group scale={1.69}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_36.geometry}
              material={materials.mudflap_rubber}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.27}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_38.geometry}
              material={materials.material}
            />
          </group>
          <group rotation={[-Math.PI, 0, -Math.PI]} scale={0.94}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_40.geometry}
              material={materials.body_plastic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_41.geometry}
              material={materials.body}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_42.geometry}
              material={materials.body_chrome}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_43.geometry}
              material={materials.body_windows}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_44.geometry}
              material={materials.body_light_glass}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_45.geometry}
              material={materials.body_focus}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_46.geometry}
              material={materials.body_back_light}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_47.geometry}
              material={materials.body_back_light_onoff}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_48.geometry}
              material={materials.body_light_goback}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_49.geometry}
              material={materials.body_rubber}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_50.geometry}
              material={materials.body_black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_51.geometry}
              material={materials.body_mirror}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_52.geometry}
              material={materials.body_signal_light_glass}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_53.geometry}
              material={materials.body_light}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_54.geometry}
              material={materials["body_int."]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_55.geometry}
              material={materials.body_resh}
            />
          </group>
          <group rotation={[-Math.PI, -0.09, -Math.PI]} scale={0.94}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_57.geometry}
              material={materials["wiper.plastic"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_58.geometry}
              material={materials["wiper.rubber"]}
            />
          </group>
          <group scale={[0.09, 0.1, 0.1]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_60.geometry}
              material={materials.texture_plate}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_62.geometry}
            material={materials.material_45}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(mercedes);
