/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

import shoe from "./shoe.glb";

export function Shoe(props) {
  const { nodes, materials } = useGLTF(shoe);
  const ref = useRef();
  useFrame((state) => {
    const t = state.clock.getElapsedTime();
    ref.current.rotation.set(
      0.1 + Math.cos(t / 4.5) / 10,
      Math.sin(t / 4) / 4,
      0.3 - (1 + Math.sin(t / 4)) / 8
    );
    ref.current.position.y = (1 + Math.sin(t / 2)) / 10;
  });
  return (
    <group {...props} dispose={null}>
      <group ref={ref}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bota_Forro.geometry}
          material={materials.Forro}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane007.geometry}
          material={materials["Polimero Cano"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane007_1.geometry}
          material={materials["Polimero Cano Forro"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bota_Polimero_Cano_2.geometry}
          material={materials["Polimero Cano"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006.geometry}
          material={materials["Nanox Marrom"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_1.geometry}
          material={materials["Nanox Borda"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane005.geometry}
          material={materials["Nanox Marrom"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane005_1.geometry}
          material={materials["Nanox Borda"]}
        />
        <group
          position={[0.59, 0.64, -0.71]}
          rotation={[-0.67, -0.14, -1.42]}
          scale={0.98}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle001.geometry}
            material={materials["Ilhos Pino"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle001_1.geometry}
            material={materials.Ilhos}
          />
        </group>
        <group
          position={[-0.49, 0.69, -0.85]}
          rotation={[-0.59, 0.09, 1.36]}
          scale={0.98}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle001_2.geometry}
            material={materials["Ilhos Pino"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle001_3.geometry}
            material={materials.Ilhos}
          />
        </group>
        <group position={[0.59, 1.17, -0.84]} rotation={[-0.39, 0.02, -1.67]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle002.geometry}
            material={materials["Ilhos Pino"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle002_1.geometry}
            material={materials.Ilhos}
          />
        </group>
        <group position={[0.68, 1.56, -0.92]} rotation={[-0.39, -0.12, -1.75]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle002_2.geometry}
            material={materials["Ilhos Pino"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle002_3.geometry}
            material={materials.Ilhos}
          />
        </group>
        <group position={[-0.55, 1.61, -1.08]} rotation={[-0.43, 0.09, 1.58]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle002_4.geometry}
            material={materials["Ilhos Pino"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle002_5.geometry}
            material={materials.Ilhos}
          />
        </group>
        <group position={[-0.47, 1.18, -0.98]} rotation={[-0.52, 0, 1.6]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle003.geometry}
            material={materials["Ilhos Pino"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle003_1.geometry}
            material={materials.Ilhos}
          />
        </group>
        <group
          position={[0.2, 0.25, 0.87]}
          rotation={[-2.22, -1.18, -2.38]}
          scale={0.88}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle.geometry}
            material={materials.Ilhos}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle_1.geometry}
            material={materials.Ilhos}
          />
        </group>
        <group
          position={[0.34, 0.27, 0.66]}
          rotation={[-1.87, -1.13, -2.5]}
          scale={0.88}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle_2.geometry}
            material={materials.Ilhos}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle_3.geometry}
            material={materials.Ilhos}
          />
        </group>
        <group
          position={[0.44, 0.35, 0.43]}
          rotation={[-1.86, -0.98, -2.17]}
          scale={0.88}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle_4.geometry}
            material={materials.Ilhos}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle_5.geometry}
            material={materials.Ilhos}
          />
        </group>
        <group
          position={[0.54, 0.43, 0.1]}
          rotation={[-1.22, -0.8, -1.66]}
          scale={0.88}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle_6.geometry}
            material={materials.Ilhos}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle_7.geometry}
            material={materials.Ilhos}
          />
        </group>
        <group
          position={[0.56, 0.53, -0.18]}
          rotation={[-1.19, -0.62, -1.62]}
          scale={0.88}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle_8.geometry}
            material={materials.Ilhos}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle_9.geometry}
            material={materials.Ilhos}
          />
        </group>
        <group
          position={[-0.28, 0.27, 0.88]}
          rotation={[-2.1, 1.25, 2.31]}
          scale={0.88}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle_10.geometry}
            material={materials.Ilhos}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle_11.geometry}
            material={materials.Ilhos}
          />
        </group>
        <group
          position={[-0.34, 0.32, 0.61]}
          rotation={[-1.79, 1.17, 2.35]}
          scale={0.88}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle_12.geometry}
            material={materials.Ilhos}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle_13.geometry}
            material={materials.Ilhos}
          />
        </group>
        <group
          position={[-0.41, 0.42, 0.33]}
          rotation={[-1.31, 1.01, 1.81]}
          scale={0.88}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle_14.geometry}
            material={materials.Ilhos}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle_15.geometry}
            material={materials.Ilhos}
          />
        </group>
        <group
          position={[-0.49, 0.51, 0.01]}
          rotation={[-1.29, 0.76, 1.74]}
          scale={0.88}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle_16.geometry}
            material={materials.Ilhos}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle_17.geometry}
            material={materials.Ilhos}
          />
        </group>
        <group
          position={[-0.51, 0.61, -0.29]}
          rotation={[-1.22, 0.58, 1.6]}
          scale={0.88}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle_18.geometry}
            material={materials.Ilhos}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle_19.geometry}
            material={materials.Ilhos}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bota_Sobre_Biqueira.geometry}
          material={materials["Sobre Biqueira"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bota_Nanox_Principal_Costura_D1.geometry}
          material={materials["Costura Marrom"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bota_Nanox_Principal_Costura_D2.geometry}
          material={materials["Costura Marrom"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bota_Nanox_Principal_Costura_E1.geometry}
          material={materials["Costura Marrom"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bota_Nanox_Principal_Costura_E2.geometry}
          material={materials["Costura Marrom"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bota_Polimero_Cano_1_Costura.geometry}
          material={materials["Costura Cinza"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bota_Nanox_Logo_Costura.geometry}
          material={materials["Costura Cinza"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bota_Borracha_Laretal_Costura_01.geometry}
          material={materials["Costura Cinza"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bota_Borracha_Laretal_Costura_02.geometry}
          material={materials["Costura Cinza"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cadarço.geometry}
          material={materials.Cadarço}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pano_Traz.geometry}
          material={materials["Pano Traz"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.CA_42454.geometry}
          material={materials["CA 42454"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Climatex.geometry}
          material={materials.CLIMATEX}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane022.geometry}
          material={materials["Palmilha Tecido"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane022_1.geometry}
          material={materials["Palmilha Base"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bota_Borracha_Lateral.geometry}
          material={materials["Borracha Lateral"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bota_Sola.geometry}
          material={materials.Sola}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane009.geometry}
          material={materials["Nanox Preto"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane009_1.geometry}
          material={materials["Nanox Borda"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload(shoe);
